# Generated by Django 6.1.1 on 2026-09-19 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('technique', 'Technique'), ('soft', 'Soft Skills'), ('langues', 'Langues'), ('outil', 'Outils'), ('autre', 'Autre')], default='technique', max_length=50)),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('average_salary', models.CharField(blank=True, help_text='Ex: 150 000 - 300 000 FCFA', max_length=100)),
                ('difficulty', models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='moyen', max_length=20)),
                ('required_skills', models.ManyToManyField(blank=True, help_text='Compétences nécessaires pour ce métier', related_name='jobs', to='core.skill')),
            ],
            options={
                'verbose_name': 'Métier',
                'verbose_name_plural': 'Métiers',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, default='Lomé', max_length=100)),
                ('education_level', models.CharField(blank=True, choices=[('college', 'Collège'), ('lycee', 'Lycée'), ('bts', 'BTS / DUT'), ('licence', 'Licence'), ('master', 'Master'), ('autre', 'Autre')], max_length=50)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('interests', models.TextField(blank=True, help_text='Ex: technologie, business, santé, création...')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='users', to='core.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
